[tool.poetry]
name = "opendoctorate-ex-public"
version = "2.6.21"
description = ""
authors = [
    {name = "MVXTP",email = "61046104+jiellll1219@users.noreply.github.com"},
    {name = "Cryin",email = "1510935847@qq.com"},
    {name = "Autumn174",email = "3410952585@qq.com"}
    "MVXTP <61046104+jiellll1219@users.noreply.github.com>",
    "Cryin <1510935847@qq.com>"
]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
flask = ">=3.1.2,<4.0.0"
requests = ">=2.32.5,<3.0.0"
pycryptodome = ">=3.23.0,<4.0.0"
msgspec = ">=0.19.0,<0.20.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
